server:
    port: ${PORT:8080}

spring:
    flyway:
        clean-disabled: true # protect prod db!

    security:
        oauth2:
            resourceserver:
                jwt:
                    issuer-uri: ${CLERK_ISSUER_URI:}
                    jwk-set-uri: ${CLERK_JWK_SET_URI:}

    datasource:
        url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
        username: ${DB_USERNAME:}
        password: ${DB_PASSWORD:}

management:
    endpoints:
        access:
            default: none
    endpoint:
        health:
            access: read-only

clerk:
    secret-key: ${CLERK_SECRET_KEY:}
    webhook-signing-secret: ${CLERK_WEBHOOK_SIGNING_SECRET:}

cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:}
